name: Build App

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM Toolchain via APT
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi g++-arm-none-eabi

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build NWA App
      run: |
        make build

    - name: Upload NWA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: numworks-app
        path: app.nwa
