name: Build App

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup ARM GCC Toolchain
      uses: supplypike/setup-bin@v1
      with:
        name: arm-none-eabi-gcc
        version: '10.3-2021.10'
        download-url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Build NWA App
      run: |
        make build

    - name: Upload NWA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: numworks-app
        path: app.nwa
